input_file: "example_data/a.md"
output_folder: "example_data/parler_multi/"
text_to_text_model: "allenai/OLMoE-1B-7B-0924-Instruct-GGUF/olmoe-1b-7b-0924-instruct-q8_0.gguf"
text_to_speech_model: "parler-tts/parler-tts-mini-multilingual-v1.1"
text_to_text_prompt: |
  You are a podcast scriptwriter generating engaging and natural-sounding conversations in JSON format. 
  The script features the following speakers:
  {SPEAKERS}
  Instructions:
  - Write dynamic, easy-to-follow dialogue.
  - Include natural interruptions and interjections.
  - Avoid repetitive phrasing between speakers.
  - Format output as a JSON conversation.
  Example:
  {
    "Speaker 1": "Welcome to our podcast! Today, we're exploring...",
    "Speaker 2": "Hi! I'm excited to hear about this. Can you explain...",
    "Speaker 1": "Sure! Imagine it like this...",
    "Speaker 2": "Oh, that's cool! But how does..."
  }
speakers:
  - id: 1
    name: Laura
    description: The main host. She explains topics clearly using anecdotes and analogies, teaching in an engaging and captivating way.
    voice_profile: Laura's voice is calm and slow in delivery, with no background noise.

  - id: 2
    name: Daniel
    description: The co-host. He keeps the conversation on track, asks curious follow-up questions, and reacts with excitement or confusion, often using interjections like hmm or umm.
    voice_profile: Daniel's voice is monotone yet slightly fast in delivery, with a very close recording that almost has no background noise.
outetts_language: "en"  # Supported languages in version 0.2-500M: en, zh, ja, ko.